-- Database Cleanup: Remove orphaned functions and unused database objects
-- This migration removes functions that reference non-existent tables and unused database objects

-- Phase 1: Drop timestamp update functions for non-existent tables
DROP FUNCTION IF EXISTS public.update_service_areas_timestamp();
DROP FUNCTION IF EXISTS public.update_bank_account_categories_timestamp();
DROP FUNCTION IF EXISTS public.update_municipality_merchants_timestamp();
DROP FUNCTION IF EXISTS public.update_autopay_timestamp();
DROP FUNCTION IF EXISTS public.update_fraud_timestamp();
DROP FUNCTION IF EXISTS public.update_municipal_notification_preferences_timestamp();

-- Phase 2: Drop household-related functions (if household management isn't implemented)
DROP FUNCTION IF EXISTS public.is_household_admin(uuid);
DROP FUNCTION IF EXISTS public.is_household_member(uuid);
DROP FUNCTION IF EXISTS public.get_household_admin_id(uuid);
DROP FUNCTION IF EXISTS public.is_in_same_household(uuid, uuid);

-- Phase 3: Drop municipal/bank account priority functions (for unimplemented features)
DROP FUNCTION IF EXISTS public.calculate_bank_account_priority(uuid);
DROP FUNCTION IF EXISTS public.update_bank_account_priorities();
DROP FUNCTION IF EXISTS public.get_next_sequence_number(uuid, uuid);

-- Phase 4: Drop duplicate user handling function
DROP FUNCTION IF EXISTS public.handle_new_user_profile();

-- Phase 5: Drop unused views (not referenced in frontend)
DROP VIEW IF EXISTS public.bill_quality_metrics CASCADE;
DROP VIEW IF EXISTS public.user_bill_summary CASCADE;

-- Phase 6: Drop unused trigram text search operator functions (pg_trgm extension cleanup)
-- These are auto-generated by the pg_trgm extension and can be safely removed if not used
DROP FUNCTION IF EXISTS public.gtrgm_in(unknown);
DROP FUNCTION IF EXISTS public.gtrgm_out(unknown);
DROP FUNCTION IF EXISTS public.gtrgm_compress(unknown);
DROP FUNCTION IF EXISTS public.gtrgm_decompress(unknown);
DROP FUNCTION IF EXISTS public.gtrgm_options(unknown);

-- Log completion
DO $$
BEGIN
  RAISE NOTICE 'Database cleanup completed successfully';
  RAISE NOTICE 'Removed orphaned functions for non-existent tables';
  RAISE NOTICE 'Removed unused household and municipal functions';
  RAISE NOTICE 'Removed unused views and extension functions';
END $$;